WebApplication2/WebApplication2/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult About()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Contact()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="Shortcut Icon" href="~/favicon.ico" type="image/x-icon">
    <title>Mahalle Baskısı</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar-inverse navbar-fixed-top" style="padding:5px;background-color:#ff9900">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="header-logo">
                    <a href="http://localhost:60300/Home/Index" class="navbar-brand" style="margin: 0px;padding:0px;"> <img src="~/Content/images/logom.png" alt="LOGO" width="100" height="40" /></a>
                </div>
            </div>
            <div class="navbar-collapse collapse">    
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("KENDİN TASARLA", "Design", "Design")</li>
                        <li>@Html.ActionLink("En Çok Satan", "Sirala", "Urun")</li>
                        <li>@Html.ActionLink("Hakkında", "About", "About")</li>
                        <li>@Html.ActionLink("İletişim", "Contact", "Contact")</li>
                    </ul>        
                <div class="nav navbar-nav navbar-right col-md-4" style="padding-top:10px;">
                    <div class="col-md-3 col-xs-7 pull-right">
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">TR <span class="caret"></span></button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <li><a href="#">EN</a></li>
                                </ul>
                            </div>   
                    </div>
                    <div class="col-md-9 col-xs-9 pull-right">
                        @using (Html.BeginForm("Search", "Urun", FormMethod.Get, new { @class = "small-input" }))
                        {
                            @Html.TextBox("Arama")
                            <input class="btn btn-default" type="submit" value="Ara" />
                        }
                    </div>
                </div>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div id="wrap">
        <div id="main">
            <div class="container body-content">
                @RenderBody()
            </div>
        </div>
    </div>
    <div id="footer" style="background-color:#ff9900">
        <a href="https://www.facebook.com/yaaklimabisitakildi"> <img src="~/Content/images/aras.png" alt="LOGO" width="40" height="40" /></a><b>  Copyright Spoon - @DateTime.Now.Year</b>
        <div style="float: right" class="footer-nav">
            <a href="http://www.facebook.com"> <img src="~/Content/images/face.jpg" alt="LOGO" width="40" height="40" /></a>
            <a href="http://www.twitter.com"> <img src="~/Content/images/twit.png" alt="LOGO" width="40" height="40" /></a>
            <a href="http://www.instagram.com"> <img src="~/Content/images/insta.png" alt="LOGO" width="40" height="40" /></a>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>